HEIGHT = 720
WIDTH = 480
CAMERA_SPEED = 1
SAMPLE_IMAGE_PATH = 'textures/apples.png'
OUTPUT_PATH = "\engine\patches"

################
### TERRAIN ####
TERRAIN_SAMPLE_PATCH_SIZE = 80
TERRAIN_MAX_NUMBER_OF_PATCHES = 100
TERRAIN_QUILTING_SIZE = 30